# https://developers.cloudflare.com/pages/functions/wrangler-configuration
name = "solid-top-loading-bar"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-17"

# https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"
